name       : mythes
version    : 1.2.4
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/hunspell/MyThes/1.2.4/mythes-1.2.4.tar.gz : 1e81f395d8c851c3e4e75b568e20fa2fa549354e75ab397f9de4b0e0790a305f
homepage   : https://hunspell.github.io/
license    : BSD-3-Clause
component  : office
summary    : Simple thesaurus library
description: |
    MyThes is a simple thesaurus that uses a structured text data file and an index file with binary search to lookup words and phrases and return information on part of speech, meanings, and synonyms.
builddeps  :
    - pkgconfig(hunspell)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
